# Generated by Django 5.2.10 on 2026-01-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0002_transaction_authorization_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payoutrequest',
            name='bank',
        ),
        migrations.AddField(
            model_name='payoutrequest',
            name='bank_code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
