# Generated by Django 5.2.10 on 2026-01-30 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0003_remove_payoutrequest_bank_payoutrequest_bank_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutrequest',
            name='account_number',
            field=models.IntegerField(default=100000000, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(9999999999)]),
            preserve_default=False,
        ),
    ]
