# Generated by Django 5.2.10 on 2026-01-22 19:17

import Main.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=400)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=33)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold')], max_length=45)),
                ('location', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('property_type', models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent'), ('lease', 'Lease'), ('shortLet', 'ShortLet'), ('land', 'Land')], max_length=60)),
                ('size', models.IntegerField()),
                ('no_of_bedrooms', models.IntegerField()),
                ('no_of_bathrooms', models.IntegerField()),
                ('swimming_pool', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('air_conditioning', models.BooleanField(default=False)),
                ('borehole', models.BooleanField(default=False)),
                ('gym', models.BooleanField(default=False)),
                ('garden', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('furnished', models.BooleanField(default=False)),
                ('security', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
                ('generator', models.BooleanField(default=False)),
                ('serviced', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_pictures')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Main.property')),
            ],
        ),
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(max_length=500)),
                ('agent_status', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, default='')),
                ('referral_code', models.CharField(blank=True, max_length=45)),
                ('invite_code', models.CharField(blank=True, max_length=45)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', Main.models.AppUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AgentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=500)),
                ('nin_number', models.CharField(max_length=11)),
                ('years_of_experience', models.CharField(max_length=32)),
                ('id_file', models.FileField(upload_to='id_files')),
                ('license_file', models.FileField(upload_to='licence_files')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_application', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
