# Generated by Django 5.2.10 on 2026-01-25 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
