# Generated by Django 5.2.10 on 2026-01-30 09:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_alter_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='no_of_bathrooms',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='no_of_bedrooms',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(1000000000)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='size',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(1000000000)]),
        ),
    ]
