# Generated by Django 5.2.10 on 2026-05-18 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_alter_property_no_of_bathrooms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='slug',
        ),
    ]
