# Generated by Django 5.2.10 on 2026-01-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_rename_propertyimages_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
    ]
