# Generated by Django 5.2.10 on 2026-01-19 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_property_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='phone_number',
            field=models.CharField(blank=True, default=''),
        ),
    ]
