# Generated by Django 5.2.10 on 2026-01-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_appuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='invite_code',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='appuser',
            name='referral_code',
            field=models.CharField(blank=True, max_length=45, unique=True),
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold')], default='available', max_length=45),
            preserve_default=False,
        ),
    ]
